# Generated by Django 3.0 on 2020-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Заголовок статьи')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст статьи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('image', models.ImageField(blank=True, upload_to='articles/', verbose_name='Изображение')),
                ('products', models.ManyToManyField(related_name='products', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('created',),
            },
        ),
    ]
